highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-  -1
google_site_verification: xxx

timezone: America/New_York

name: Activerecord • A Simple ORM with history.
description: Transform your PHP Development Process
url: "https://wriver4.github.io"

logo: assets/images/logo.png